### PR TITLE
Extract public API typings into libdef

### LINKED ISSUE #157: Flow type complains about several issues with react-flip-move
Like [this one](https://github.com/joshwcomeau/react-flip-move/blob/master/src/enter-leave-presets.js#L61)

```
node_modules/react-flip-move/src/enter-leave-presets.js:61
 61: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression
```

I'm pretty sure you should be able to remove that. Actually, there are quite a few flow-related issues. I think it may be best to remove `src` from the `package.json`. But I could be wrong. I've not done much with flow in OSS yet...

Here are all the errors I get:

<details>
<summary>all of the errors</summary>

```
node_modules/react-flip-move/lib/FlipMove.js.flow:57
 57:   state = {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:69
 69:   childrenData: {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:82
 82:   parentData: NodeData = {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:91
 91:   heightPlaceholderData: NodeData = {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:101
101:   remainingAnimations = 0;
       ^^^^^^^^^^^^^^^^^^^^^^^^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:102
102:   childrenToAnimate: Array<string> = [];
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:164
164:   runAnimation = () => {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:180
180:   doesChildNeedToBeAnimated = (child: ChildData) => {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/FlipMove.js.flow:357
357:     requestAnimationFrame(() => {
         ^^^^^^^^^^^^^^^^^^^^^ identifier `requestAnimationFrame`. Could not resolve name

node_modules/react-flip-move/lib/dom-manipulation.js.flow:152
152:     [string]: number,
                ^ Unexpected token ]

node_modules/react-flip-move/lib/enter-leave-presets.js.flow:59
 59: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/lib/enter-leave-presets.js.flow:61
 61: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/lib/enter-leave-presets.js.flow:63
 63: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/lib/enter-leave-presets.js.flow:65
 65: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/lib/helpers.js.flow:40
 40: function memoizeString<T>(fn: (string) => T): (string) => T {
                                            ^^ Unexpected token =>

node_modules/react-flip-move/lib/prop-converter.js.flow:63
 63:     static defaultProps = {
         ^ Experimental class static field usage. Class static fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_static_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/lib/typings.js.flow:5
  5:   [string]: string,
              ^ Unexpected token ]

node_modules/react-flip-move/src/FlipMove.js:57
 57:   state = {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:69
 69:   childrenData: {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:82
 82:   parentData: NodeData = {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:91
 91:   heightPlaceholderData: NodeData = {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:101
101:   remainingAnimations = 0;
       ^^^^^^^^^^^^^^^^^^^^^^^^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:102
102:   childrenToAnimate: Array<string> = [];
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:164
164:   runAnimation = () => {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:180
180:   doesChildNeedToBeAnimated = (child: ChildData) => {
       ^ Experimental class instance field usage. Class instance fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_instance_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/FlipMove.js:357
357:     requestAnimationFrame(() => {
         ^^^^^^^^^^^^^^^^^^^^^ identifier `requestAnimationFrame`. Could not resolve name

node_modules/react-flip-move/src/dom-manipulation.js:152
152:     [string]: number,
                ^ Unexpected token ]

node_modules/react-flip-move/src/enter-leave-presets.js:59
 59: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/src/enter-leave-presets.js:61
 61: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/src/enter-leave-presets.js:63
 63: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/src/enter-leave-presets.js:65
 65: // $FlowFixMe
     ^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

node_modules/react-flip-move/src/helpers.js:40
 40: function memoizeString<T>(fn: (string) => T): (string) => T {
                                            ^^ Unexpected token =>

node_modules/react-flip-move/src/prop-converter.js:63
 63:     static defaultProps = {
         ^ Experimental class static field usage. Class static fields are an active early stage feature proposal that may change. You may opt-in to using them anyway in Flow by putting `esproposal.class_static_fields=enable` into the [options] section of your .flowconfig.

node_modules/react-flip-move/src/typings.js:5
  5:   [string]: string,
              ^ Unexpected token ]


Found 34 errors
```

</details>

### PR DESCRIPTION
**Pull request by Hypnosphi**
Should partially fix #157. The `react-flip-move_v2.9.x.js` file is exactly the same as the one commited in https://github.com/flowtype/flow-typed/pull/844, and they have to stay in sync. Ideally they shouldn't be touched though, unless a minor version comes and brings some new API

### CODE REVIEW

File: src/typings.js [hunk 1]
```diff
@@ -1,85 +1,35 @@
...
+  ClientRect,
+  ElementShape,
+  ChildrenHook,
+  GetPosition,
+  VerticalAlignment,
+  FlipMoveDefaultProps,
+  Hooks,
+  DelegatedProps,
+  FlipMoveProps,
+} from 'react-flip-move'; // eslint-disable-line import/extensions
```
Comment (Hypnosphi) [inline src/typings.js]: This is a way to keep using the same typings externally and internally

Comment (joshwcomeau) [inline src/typings.js]: Cool! Makes sense to me.

**Comment by joshwcomeau** [comment]
@Hypnosphi I'm guessing we should wait on the PR to flow-typed before launching this?

I'm out of town for the next 4 days (going to React Europe :D), so my responses may be slow. I'll try to pop in periodically because I'd love to get the Flow issues fixed, but apologies in advance if I'm unable.

**Comment by Hypnosphi** [comment]
People would still have to ignore `node_modules/react-flip-move` because of `src`

And there was a change in deps: https://github.com/joshwcomeau/react-flip-move/pull/158/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L71

**Comment by Hypnosphi** [comment]
>we should wait on the PR to flow-typed before launching this?

That totally makes sense. I think I'll add a "Flow support" section to readme then

**Comment by Hypnosphi** [comment]
https://github.com/flowtype/flow-typed/pull/844 is merged

**Comment by joshwcomeau** [comment]
Awesome, let's push this out then!

I'm at work but I'm setting a reminder to merge and publish this tonight (in ~8 hours or so)
